version: '3'
services:
  db:
    image: postgres:15
    command: -p 5436
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: argusadmin
      POSTGRES_DB: medplat
    ports:
      - "5436:5436"
    volumes:
      - ./temp/data:/var/lib/postgresql/data
      - ./db_init.sh:/docker-entrypoint-initdb.d/db_init.sh
    networks:
      - medplat_net

  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8181:8181"
    volumes:
      - ./medplat-ui:/usr/ui
      - ./medplat-web/src:/usr/web/src
      - ./medplat-web/pom.xml:/usr/web/pom.xml
      - ./temp/.m2:/root/.m2
      - ./entrypoint.sh:/usr/entrypoint.sh
    networks:
      - medplat_net

networks:
  medplat_net:


