version: '3'
services:
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: argusadmin
      POSTGRES_DB: medplat
    ports:
      - "5432:5432"
    volumes:
     - type: bind
       source: /home/nehil/repo/medplat/data
       target: /var/lib/postgresql/data
       bind:
        create_host_path: true
    networks:
      - medplat_net

  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8181:8181"
    volumes:
      - type: bind
        source: /home/nehil/repo/medplat/medplat-ui
        target: /usr/ui/medplat-ui
        bind:
        create_host_path: true
      - type: bind
        source: /home/nehil/repo/medplat/medplat-web
        target: /usr/medplat-web
        bind:
        create_host_path: true
    networks:
      - medplat_net

networks:
  medplat_net:

