services:
  db:
    image: postgres:15
    command: -p 5436
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: argusadmin
      POSTGRES_DB: medplat
    ports:
      - "5436:5436"
    volumes:
      - medplat-db-data:/var/lib/postgresql/data
      - ./db_init.sh:/docker-entrypoint-initdb.d/db_init.sh
    networks:
      - medplat_net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -p 5436"]
      interval: 5s
      timeout: 5s
      retries: 10

  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8181:8181"
    dns:
      - 8.8.8.8
      - 8.8.4.4
    volumes:
      - ./medplat-ui:/usr/ui/medplat-ui
      - ./medplat-web/:/usr/web
      - medplat-m2-cache:/root/.m2
    networks:
      - medplat_net
    depends_on:
      db:
        condition: service_healthy

networks:
  medplat_net:

volumes:
  medplat-db-data:
  medplat-m2-cache:
