package com.argusoft.medplat.ncddnhdd.enums;

/**
 * Define status of ncd.
 * @author smeet
 */
public enum Status {
    SUSPECTED, CONFIRMED, TREATMENT_STARTED, REFERRED, CONFIRMATION_PENDING,CONTROLLED,UNCONTROLLED,
    UNDERTREATMENT_CONTROLLED, UNDERTREATMENT, UNDERTREATMENT_UNCONTROLLED, NORMAL, REFERRED_CONSULTANT , FOLLOWUP, REFERRED_MO,
    REFERRED_BACK_CONSULTANT, REFERRED_HIGHER_CENTER, REFERRED_BACK_MO, MOBILE_REFERRED, NO_ABNORMALITY
}
